default_app_name=fast_cpp_server
default_config_dir=/home/cs/DockerRoot/fast_cpp_server/config/v2
default_swagger_res_dir=/usr/share/fast_cpp_server/swagger-res/res
default_logger_dir=/var/fast_cpp_server/logs/
default_temp_dir=/tmp/fast_cpp_server/

app_name=fast_cpp_server
config_dir=/home/cs/DockerRoot/fast_cpp_server/config/v2
swagger_res_dir=/opt/fast_cpp_server/share/swagger-res/res
logger_dir=/var/log/fast_cpp_server/
temp_dir=/tmp/fast_cpp_server/
# If console_output is set to true, the application will output logs to the console.
# This is useful for debugging purposes, but it may not be suitable for production environments.
console_output=true
load_json_version=v2